### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by MasterSwift** [yannickl/Reactions#13]
Hey I was wondering if you would be able to add in a feature to this framework.

Introduce spectral emotions.

**Comment by yannickl** [comment]
Hi @MasterSwift,

I believe I undertstand your need but I don't know how to design that easily in the control. For the moment when you drag over the reactions they simply grow or shrink, I don't know how to manage the "spectral emotions".

Moreover I would keep the same interactions than those of Facebook to not make the control more difficult to use.
