### ISSUE TITLE
feedback for feedback delegate

### ISSUE THREAD

**Issue by MorekeysOfficial** [yannickl/Reactions#24]
Could you explain how or what you can do with the feedback delegate because currently, it's just sitting in the swift file empty and the description doesn't really explain anything?

**Comment by yannickl** [comment]
The `ReactionFeedbackDelegate` allows the receiver to know in which state is the `ReactionSelector`. This delegate is not mandatory, you should implement it if you want to give more feedback to your user.

If you check out the example project you will notice that it updates the feedback label:

<img width="361" alt="screen shot 2018-08-20 at 15 54 40" src="https://user-images.githubusercontent.com/798235/44344617-6b2b1980-a491-11e8-8def-b1374721a15b.png">

**Comment by MorekeysOfficial** [comment]
I see thank you
