### ISSUE TITLE
Type 'Reaction.facebook' has no member 'openhand'

### ISSUE THREAD

**Issue by Rjmaurya13** [yannickl/Reactions#26]
Type 'Reaction.facebook' has no member 'openhand'

**Comment by yannickl** [comment]
The `Reaction.facebook` only owns these properties: `like`, `love`, `haha`, `wow`,  `sad` and `angry`. See: https://github.com/yannickl/Reactions/blob/c380f493d01796cdcc4ae0abb5da60d53fc51ec8/Sources/FacebookReactions.swift#L33-L61
