### ISSUE TITLE
Deployment Target Version for Cocoa Touch framework is 10.0, should be 8.0

### ISSUE THREAD

**Issue by pedromancheno** [yannickl/Reactions#9]
I was trying to use the framework through Carthage in my project which supports iOS 8.0 and got an error as the minimum deployment target version was set to 10.0

I've updated the project and it works fine now. You only need to lower the number for the Cocoa Framework target.

**Comment by yannickl** [comment]
Indeed, it was an oversight. Thank you for the hint. 👍
